In [3]:
"""Q1. What is the relationship between polynomial functions and kernel functions in machine learning algorithms?

    Ans: Polynomial functions can be used as kernel functions to implicitly map input data into a higher-dimensional feature space in machine learning algorithms. \
         This allows linear algorithms to be applied to non-linear problems, which can be computationally efficient, especially for high-dimensional feature spaces.
"""

'Q1. What is the relationship between polynomial functions and kernel functions in machine learning algorithms?\n\n    Ans: Polynomial functions can be used as kernel functions to implicitly map input data into a higher-dimensional feature space in machine learning algorithms.          This allows linear algorithms to be applied to non-linear problems, which can be computationally efficient, especially for high-dimensional feature spaces.\n'

In [4]:
"""Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?"""

# from sklearn.svm import SVC
# classifier = SVC(kernel='ploy', degree=3)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)

'Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?'

In [5]:
"""Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

    Ans: Increasing the value of epsilon in Support Vector Regression (SVR) leads to an increase in the number of support vectors. This is because larger values of epsilon allow 
         more data points to be within the margin of tolerance, resulting in a larger margin and more support vectors required to define it.
"""

'Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?\n\n    Ans: Increasing the value of epsilon in Support Vector Regression (SVR) leads to an increase in the number of support vectors. This is because larger values of epsilon allow \n         more data points to be within the margin of tolerance, resulting in a larger margin and more support vectors required to define it.\n'

In [6]:
"""Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter affect the performance of Support Vector Regression (SVR)? 
Can you explain how each parameter works and provide examples of when you might want to increase or decrease its value?

    Ans: 1. Kernel function: The choice of kernel function determines how the input data is mapped to a higher-dimensional feature space. Common kernel functions include linear, 
                polynomial, and radial basis function (RBF). If the data is linearly separable, a linear kernel can be used. If the data is non-linear, a polynomial or 
                RBF kernel may be more appropriate. The choice of kernel function should be based on the characteristics of the data.
         2. C parameter: The C parameter controls the trade-off between the model's complexity and its ability to fit the training data. A large value of C allows the model to 
                fit the training data more closely, but may lead to overfitting. A small value of C results in a simpler model but may underfit the data. The value of C should 
                be chosen based on the size of the training data and the desired level of generalization.
         3. Epsilon parameter: The epsilon parameter controls the size of the margin of tolerance around the predicted values. A larger value of epsilon allows more data points 
                to be within the margin of tolerance, resulting in a larger margin and more support vectors required to define it. A smaller value of epsilon leads to a smaller 
                margin and fewer support vectors. The choice of epsilon should be based on the desired level of tolerance around the predicted values.
         4. Gamma parameter: The gamma parameter controls the influence of each training example. A small value of gamma means that each training example has a large influence,
                resulting in a smoother decision boundary. A large value of gamma means that each training example has a smaller influence, resulting in a more complex decision
                boundary. The choice of gamma should be based on the size of the dataset and the desired level of generalization.

"""

"Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter affect the performance of Support Vector Regression (SVR)? \nCan you explain how each parameter works and provide examples of when you might want to increase or decrease its value?\n\n    Ans: 1. Kernel function: The choice of kernel function determines how the input data is mapped to a higher-dimensional feature space. Common kernel functions include linear, \n                polynomial, and radial basis function (RBF). If the data is linearly separable, a linear kernel can be used. If the data is non-linear, a polynomial or \n                RBF kernel may be more appropriate. The choice of kernel function should be based on the characteristics of the data.\n         2. C parameter: The C parameter controls the trade-off between the model's complexity and its ability to fit the training data. A large value of C allows the model to \n                fit the training data more closely, but 

In [7]:
"""Q5. Assignment:
L Import the necessary libraries and load the dataset
L Split the dataset into training and testing sets
L Preprocess the data using any technique of your choice (e.g. scaling, normalimation)
L Create an instance of the SVC classifier and train it on the training data
L Use the trained classifier to predict the labels of the testing data
L Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,
precision, recall, F1-scoreK
L Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to
improve its performance
L Train the tuned classifier on the entire dataset
L Save the trained classifier to a file for future use.

You can use any dataset of your choice for this assignment, but make sure it is suitable for
classification and has a sufficient number of features and samples."""

'Q5. Assignment:\nL Import the necessary libraries and load the dataset\nL Split the dataset into training and testing sets\nL Preprocess the data using any technique of your choice (e.g. scaling, normalimation)\nL Create an instance of the SVC classifier and train it on the training data\nL Use the trained classifier to predict the labels of the testing data\nL Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,\nprecision, recall, F1-scoreK\nL Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to\nimprove its performance\nL Train the tuned classifier on the entire dataset\nL Save the trained classifier to a file for future use.\n\nYou can use any dataset of your choice for this assignment, but make sure it is suitable for\nclassification and has a sufficient number of features and samples.'

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# we are using Diamond Dataset to Classify Cut type

In [2]:
dataset = sns.load_dataset('diamonds')
dataset.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53940 non-null  float64 
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64 
 5   table    53940 non-null  float64 
 6   price    53940 non-null  int64   
 7   x        53940 non-null  float64 
 8   y        53940 non-null  float64 
 9   z        53940 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB


In [4]:
from sklearn.preprocessing import OneHotEncoder
## create an instance of OneHotEncoder
encoder = OneHotEncoder()
# fitting the encoder to the dataframe and transforming the categorical variable
encoded = encoder.fit_transform(dataset[['color','clarity']])

In [5]:
en_df = pd.DataFrame(encoded.toarray() , columns = encoder.get_feature_names_out())
data = pd.concat([dataset, en_df], axis = 1)
data.drop('color',axis=1,inplace=True)
data.drop('clarity',axis=1,inplace=True)

In [6]:
data.head()

carat      cut  depth  table  price     x     y     z  color_D  color_E  \
0   0.23    Ideal   61.5   55.0    326  3.95  3.98  2.43      0.0      1.0   
1   0.21  Premium   59.8   61.0    326  3.89  3.84  2.31      0.0      1.0   
2   0.23     Good   56.9   65.0    327  4.05  4.07  2.31      0.0      1.0   
3   0.29  Premium   62.4   58.0    334  4.20  4.23  2.63      0.0      0.0   
4   0.31     Good   63.3   58.0    335  4.34  4.35  2.75      0.0      0.0   

   ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  \
0  ...      0.0      0.0         0.0         0.0          0.0          1.0   
1  ...      0.0      0.0         0.0         0.0          1.0          0.0   
2  ...      0.0      0.0         0.0         0.0          0.0          0.0   
3  ...      1.0      0.0         0.0         0.0          0.0          0.0   
4  ...      0.0      1.0         0.0         0.0          0.0          1.0   

   clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0          0.0          0.0           0.0           0.0  
1          0.0          0.0           0.0           0.0  
2          1.0          0.0           0.0           0.0  
3          0.0          1.0           0.0           0.0  
4          0.0          0.0           0.0           0.0  

[5 rows x 23 columns]

In [7]:
features_list = ['carat', 'depth', 'table', 'price', 'x', 'y', 'z', 'color_D', 'color_E', 'color_F', 'color_G', 'color_H', 'color_I', 'color_J', 
                 'clarity_I1', 'clarity_IF', 'clarity_SI1', 'clarity_SI2', 'clarity_VS1', 'clarity_VS2', 'clarity_VVS1', 'clarity_VVS2']
target = 'cut'

In [8]:
X = data[features_list]
y = data[target]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=69)

In [10]:
import pickle
from sklearn.preprocessing import StandardScaler

# Standard Scaling - Standardization
def standard_scaler(X_train, X_test):
#     scaling the data
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
#     Saving the model as pickle file
    file = open('scaler.pkl','wb')
    pickle.dump(scaler, file)
    file.close()
    
    return X_train_scaled, X_test_scaled

X_train_scaled, X_test_scaled = standard_scaler(X_train, X_test)

In [11]:
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(X_train_scaled, y_train)
y_p = classifier.predict(X_test_scaled)

In [12]:
print(y_p)

['Very Good' 'Ideal' 'Very Good' ... 'Ideal' 'Ideal' 'Ideal']


In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test, y_p))
print(confusion_matrix(y_test, y_p))
print(classification_report(y_test, y_p))

0.7153009516747003
[[ 343   91    4   11    2]
 [  44  788   46  172  442]
 [   4    7 5971  306  178]
 [   2   40  505 3357  266]
 [   2  254 1014 1217 1116]]
              precision    recall  f1-score   support

        Fair       0.87      0.76      0.81       451
        Good       0.67      0.53      0.59      1492
       Ideal       0.79      0.92      0.85      6466
     Premium       0.66      0.81      0.73      4170
   Very Good       0.56      0.31      0.40      3603

    accuracy                           0.72     16182
   macro avg       0.71      0.67      0.68     16182
weighted avg       0.70      0.72      0.69     16182



In [14]:
from sklearn.model_selection import RandomizedSearchCV

p = {
    'C':[0.1,1,10,100,1000],
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}

clf = RandomizedSearchCV(SVC(), param_distributions=p, cv=5, verbose=3)

In [ ]:
clf.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.680 total time= 1.2min
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.675 total time= 1.3min
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.675 total time= 1.3min
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.683 total time= 1.3min
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.680 total time= 1.3min


In [ ]:
print(clf.best_estimator_)
y_p2 = clf.predict(X_test_scaled)
print(accuracy_score(y_test, y_p2))
print(confusion_matrix(y_test, y_p2))
print(classification_report(y_test, y_p2))

In [ ]:
s = StandardScaler()
X_scaled =  s.fit_transform(X)
file = open('Entire_dataset_scaler.pkl','wb')
pickle.dump(s, file)
file.close()

In [ ]:
classifier = SVC()
classifier.fit(X_scaled, y)

In [ ]:
pickle.dump(classifier, open('SVC.pkl','wb'))